### ISSUE TITLE
[Bug] Amecs + ImmersiveAircraft  (Invalid key -1)

### ISSUE THREAD

**Issue by MrBeat93** [Luke100000/ImmersiveAircraft#207] opened 2024-09-29 16:41 UTC
Minecraft: 1.20.1
Fabric Loader: 0.16.5
Fabric API: 0.92.2
ImmersiveAircraft: 1.1.2
Amecs: 1.3.10

Whenever I close any interface ingame the live log gives 8 of this error:
```
:########## GL ERROR ##########
:@ Render
:65539: Invalid key -1
```
This occurs when these are binded to something
```
Backward
Down
Forward
Left
Pull controller
Push controller
Right
Up
```

**Comment by Luke100000** [comment] 2024-11-04 16:43
Does it cause issues tho? OpenGL likes to yap a lot, but it does not always cause problems.

**Comment by MrBeat93** [comment] 2024-11-04 16:47
It works fine. No gameplay issue.

**Comment by Luke100000** [comment] 2024-11-04 16:50
Then I will close this as intended, using -1 to indicate an unassigned key is afaik the intended way and I'm not aware of a workaround.

**Closed as completed by Luke100000** 2024-11-04 16:50 UTC
